### ISSUE TITLE
Deleted Documents Not Removed

### ISSUE THREAD

**Issue by MatthewHallCom** [devloopsnet/laravel-scout-typesense-engine#2]
It looks like right now Deleted Documents are not being removed from Typesense.

It may have to do with how many documents are in the Collection as it looks like the current function is using `getDocuments()` and expecting the ID to be there.

I've dug into fixing this but as far as I can tell there is no "clean" way to do it with the existing Client.

A similar issue exists for `upsertDocument` - instead of a global `getDocuments` it should attempt a `getDocumentById` type call as the Document may not exist in the getDocuments response.

I believe this will need functionality to be added both to the upstream PHP library as well as this library - the ability to directly retrieve a Document by an ID as well as to Delete it by an ID. I'm happy to move forward with implementing that approach just want to make sure you're open to them and that approach!

**Comment by AbdullahFaqeir** [comment]
Hello @matthewhall-ca,

I'm very sorry for the very late reply as I've been downed in a hectic couple of months with work.

I'd like to ask you if you're still interested with the fix you offered and if I can help you further with it.

**Comment by AbdullahFaqeir** [comment]
Hey @matthewhall-ca,

I understand the approach you're suggesting, yet after I went over my code once again, I am actually following this approach, please check the link below.

https://github.com/devloopsnet/typesense-php/blob/b9d00fb9afe23a4d0debe53b3e6b6a514c687b14/src/Documents.php#L133 

and please try to follow how it work from the outside-in.

I'm not actually fetching all the documents when calling ``getDocuments()`` I'm only getting a variable which holds an object of the ``Documents`` class which is referenced in the url above, and the url above explains what actually happens when `the Document may not exist in the getDocuments response` there's actually no response because I never fetch all the documents anywhere in the code as you know it's not efficient.

Yet that doesn't mean that you're actual issue "Deleted Documents Not Removed" does not exist, I'd like if you can help me debug this issue more so we can fix it.

**Comment by MatthewHallCom** [comment]
Thanks @AbdullahFaqeir we've moved on to another approach now. Have a good day
